
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Dec 10 2024 16:58:03 IST (Dec 10 2024 11:28:03 UTC)

// Verification Directory fv/washing 

module washing(clk, reset, door_close, start, filled, detergent_added,
     cycle_timeout, drained, spin_timeout, door_lock, motor_on,
     fill_value_on, drain_value_on, done, soap_wash, water_wash);
  input clk, reset, door_close, start, filled, detergent_added,
       cycle_timeout, drained, spin_timeout;
  output door_lock, motor_on, fill_value_on, drain_value_on, done,
       soap_wash, water_wash;
  wire clk, reset, door_close, start, filled, detergent_added,
       cycle_timeout, drained, spin_timeout;
  wire door_lock, motor_on, fill_value_on, drain_value_on, done,
       soap_wash, water_wash;
  wire [2:0] current_state;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  nr03d1 g1476__2398(.A1 (n_18), .A2 (n_22), .A3 (n_37), .ZN (n_39));
  lanlq1 water_wash_reg(.EN (n_35), .D (n_38), .Q (water_wash));
  aoim21d1 g1477__5107(.A (n_4), .B1 (n_15), .B2 (soap_wash), .ZN
       (n_38));
  oai21d1 g1478__6260(.A (n_24), .B1 (soap_wash), .B2 (n_28), .ZN
       (n_37));
  lanhq1 soap_wash_reg(.E (n_34), .D (n_26), .Q (soap_wash));
  aoi311d1 g1481__4319(.A (n_31), .B (n_23), .C1 (n_16), .C2
       (water_wash), .C3 (drained), .ZN (n_35));
  nd03d0 g1480__8428(.A1 (n_32), .A2 (n_29), .A3 (n_20), .ZN (n_34));
  oai211d1 g1486__5526(.A (n_17), .B (n_21), .C1 (n_25), .C2
       (spin_timeout), .ZN (n_33));
  inv0d0 g1485(.I (n_31), .ZN (n_32));
  lanhq1 door_lock_reg(.E (n_27), .D (n_19), .Q (door_lock));
  oai211d1 g1484__6783(.A (n_29), .B (n_28), .C1 (current_state[2]),
       .C2 (n_12), .ZN (n_30));
  lanhq1 drain_value_on_reg(.E (n_27), .D (n_14), .Q (drain_value_on));
  nd03d0 g1487__3680(.A1 (n_28), .A2 (n_26), .A3 (n_25), .ZN (n_31));
  aoi21d1 g1491__1617(.A (n_23), .B1 (n_10), .B2 (spin_timeout), .ZN
       (n_24));
  lanhq1 fill_value_on_reg(.E (n_27), .D (n_13), .Q (fill_value_on));
  oai211d1 g1492__2802(.A (n_27), .B (n_21), .C1 (n_20), .C2 (drained),
       .ZN (n_22));
  inv0d0 g1497(.I (n_18), .ZN (n_19));
  oai21d1 g1498__1705(.A (n_16), .B1 (water_wash), .B2 (n_1), .ZN
       (n_17));
  lanhq1 motor_on_reg(.E (n_27), .D (n_11), .Q (motor_on));
  nr02d0 g1495__5122(.A1 (n_29), .A2 (detergent_added), .ZN (n_23));
  nd12d1 g1496__8246(.A1 (n_15), .A2 (filled), .ZN (n_28));
  oai22d1 g1500__7098(.A1 (n_9), .A2 (n_3), .B1 (n_8), .B2
       (spin_timeout), .ZN (n_14));
  nr02d0 g1499__6131(.A1 (n_15), .A2 (filled), .ZN (n_13));
  lanhq1 done_reg(.E (n_27), .D (n_6), .Q (done));
  aoi21d1 g1501__1881(.A (n_26), .B1 (door_close), .B2 (start), .ZN
       (n_18));
  inv0d0 g1507(.I (n_11), .ZN (n_12));
  inv0d0 g1508(.I (n_20), .ZN (n_16));
  inv0d0 g1502(.I (n_10), .ZN (n_25));
  nd04d1 g1510__5115(.A1 (current_state[1]), .A2 (n_9), .A3
       (current_state[0]), .A4 (cycle_timeout), .ZN (n_21));
  nr03d1 g1509__7482(.A1 (cycle_timeout), .A2 (n_7), .A3 (n_2), .ZN
       (n_11));
  nr02d1 g1506__4733(.A1 (current_state[1]), .A2 (n_8), .ZN (n_10));
  nd03d1 g1511__6161(.A1 (n_7), .A2 (n_9), .A3 (current_state[0]), .ZN
       (n_15));
  nr02d0 g1503__9315(.A1 (n_8), .A2 (n_0), .ZN (n_6));
  nd02d1 g1512__9945(.A1 (n_5), .A2 (current_state[2]), .ZN (n_20));
  nd02d1 g1505__2883(.A1 (n_5), .A2 (n_9), .ZN (n_26));
  nd02d1 g1504__2346(.A1 (n_4), .A2 (current_state[1]), .ZN (n_29));
  nd02d0 g1513__1666(.A1 (n_2), .A2 (n_1), .ZN (n_3));
  nr02d1 g1516__7410(.A1 (current_state[1]), .A2 (current_state[0]),
       .ZN (n_5));
  nd02d1 g1517__6417(.A1 (current_state[2]), .A2 (current_state[1]),
       .ZN (n_27));
  nr02d1 g1515__5477(.A1 (current_state[2]), .A2 (current_state[0]),
       .ZN (n_4));
  nd02d1 g1514__2398(.A1 (current_state[0]), .A2 (current_state[2]),
       .ZN (n_8));
  inv0d0 g1522(.I (drained), .ZN (n_1));
  inv0d0 g1518(.I (spin_timeout), .ZN (n_0));
  inv0d0 g1521(.I (reset), .ZN (n_36));
  dfcrb1 \current_state_reg[0] (.CDN (n_36), .CP (clk), .D (n_39), .Q
       (current_state[0]), .QN (n_2));
  dfcrb1 \current_state_reg[2] (.CDN (n_36), .CP (clk), .D (n_33), .Q
       (current_state[2]), .QN (n_9));
  dfcrb1 \current_state_reg[1] (.CDN (n_36), .CP (clk), .D (n_30), .Q
       (current_state[1]), .QN (n_7));
       
pc3d01 Ireset(.PAD(reset),.CIN(reset));
pc3c01 Iclk(.CCLK(clk),.CP(clk));


pc3d01 Idoor_close(.PAD(door_close),.CIN(door_close));
pc3d01 Istart(.PAD(start),.CIN(start));
pc3d01 Ifilled(.PAD(filled),.CIN(filled));
pc3d01 Idetergent_added(.PAD(detergent_added),.CIN(detergent_added));
pc3d01 Icycle_timeout(.PAD(cycle_timeout),.CIN(cycle_timeout));
pc3d01 Idrained(.PAD(drained),.CIN(drained));
pc3d01 Ispin_timeout(.PAD(spin_timeout),.CIN(spin_timeout));




pc3d01 Odoor_lock(.PAD(door_lock),.CIN(door_lock));
pc3d01 Omotor_on(.PAD(motor_on),.CIN(motor_on));
pc3d01 Ofill_value_on(.PAD(fill_value_on),.CIN(fill_value_on));
pc3d01 Odrain_value_on(.PAD(drain_value_on),.CIN(drain_value_on));
pc3d01 Odone(.PAD(done),.CIN(done));
pc3d01 Osoap_wash(.PAD(soap_wash),.CIN(soap_wash));
pc3d01 Owater_wash(.PAD(water_wash),.CIN(water_wash));
       
       
endmodule

